# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
    inputs:
      loader:
        required: true
        type: choice
        options:
        - fabric
        - forge
      version:
        required: true
        type: choice
        options:
        - '1.18'
      target:
        required: true
        type: string
        
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: create .env
      run: |
        echo "API_KEY=$API_KEY" >> .env.production
      env:
        API_KEY: ${{ secrets.API_KEY }}
    - run: npm ci
    - run: node index.js ${{ github.event.inputs.loader }} ${{ github.event.inputs.version }} ${{ github.event.inputs.target }}
